INSERT INTO completion (completion_year, status) VALUES (2025, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2025, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2025, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2024, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2024, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2024, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2023, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2023, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2023, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2022, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2022, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2022, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2021, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2021, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2021, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2020, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2020, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2020, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2019, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2019, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2019, 'Started');