INSERT INTO completion (completion_year, status) VALUES (2030, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2030, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2030, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2029, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2029, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2029, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2028, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2028, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2028, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2027, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2027, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2027, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2026, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2026, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2026, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2025, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2025, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2025, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2024, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2024, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2024, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2023, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2023, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2023, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2022, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2022, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2022, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2021, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2021, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2021, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2020, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2020, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2020, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2019, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2019, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2019, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2018, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2018, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2018, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2017, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2017, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2017, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2016, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2016, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2016, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2015, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2015, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2015, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2014, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2014, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2014, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2013, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2013, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2013, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2012, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2012, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2012, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2011, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2011, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2011, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2010, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2010, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2010, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2009, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2009, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2009, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2008, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2008, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2008, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2007, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2007, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2007, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2006, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2006, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2006, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2005, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2005, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2005, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2004, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2004, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2004, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2003, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2003, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2003, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2002, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2002, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2002, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2001, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2001, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2001, 'Started');
INSERT INTO completion (completion_year, status) VALUES (2000, 'Complete');
INSERT INTO completion (completion_year, status) VALUES (2000, 'In progress');
INSERT INTO completion (completion_year, status) VALUES (2000, 'Started');